#!/bin/bash

OUT_PREFIX=$1

set -e
set -o pipefail

if [ "$TARGET" = "ubuntu:22.04" ]; then
	RUBY_VERSION="3.1.2"
else
	RUBY_VERSION="2.4.4"
fi

echo "-----> Building pkgr ${VERSION}..."
PREFIX=/app/vendor/ruby buildcurl ruby "$RUBY_VERSION" | tar xz -C $OUT_PREFIX

GEM_HOME="$($OUT_PREFIX/bin/gem env GEM_HOME)"
pushd "$GEM_HOME"
buildcurl rubygem-pkgr $VERSION | tar xz -C .
popd

for bin in $GEM_HOME/bin/* ; do
	ln -sf $bin $OUT_PREFIX/bin/
done

echo "-----> Done."
