#!/usr/bin/env bash
# Build Path: /app/.heroku/python/
# Build Deps: libraries/sqlite

OUT_PREFIX=$1

set -e
set -o pipefail

curl_flags="-L"
# issue with let's encrypt, need to update base image
if [ "$TARGET" = "sles:12" ]; then
  curl_flags="$curl_flags -k"
fi

# sqlite version does not matter
buildcurl sqlite 1.2.3 | tar xz -C $OUT_PREFIX

VERSION=${VERSION:=2.7.6}
dep_dirname="Python-$VERSION"

echo "Building $dep_dirname..."
SOURCE_TARBALL="https://python.org/ftp/python/$VERSION/$dep_dirname.tgz"
curl $curl_flags $SOURCE_TARBALL | tar xz --strip-components=1

./configure --prefix=$OUT_PREFIX
make -j ${JOBS:=1}
make install

if test -f $OUT_PREFIX/bin/python3 ; then
	ln -s $OUT_PREFIX/bin/python3 $OUT_PREFIX/bin/python
fi

if test -f $OUT_PREFIX/bin/pip3 ; then
	ln -s $OUT_PREFIX/bin/pip3 $OUT_PREFIX/bin/pip
fi

rm -rf $OUT_PREFIX/lib/python*/{__pycache__,test}

echo "-----> Done."
