#!/bin/bash

set -e
set -o pipefail

OUT_PREFIX="$1"
RUBY_PREFIX="/app/vendor/ruby"
GEM="pkgr"
export LANG="en_US.UTF-8"
export GEM_HOME="$OUT_PREFIX"

mkdir -p $RUBY_PREFIX

if [ "$TARGET" = "ubuntu:22.04" ]; then
	RUBY_VERSION="3.1.2"
else
	RUBY_VERSION="2.4.4"
fi

PREFIX=$RUBY_PREFIX buildcurl ruby "$RUBY_VERSION" | tar xz -C $RUBY_PREFIX

echo "-> Building rubygem-$GEM $VERSION..."
if [ "${#VERSION}" = "40" ] || [ "${#VERSION}" = "7" ]; then
	git clone https://github.com/crohr/pkgr.git
	pushd pkgr
	git reset --hard "$VERSION"
	$RUBY_PREFIX/bin/gem build $GEM.gemspec
	$RUBY_PREFIX/bin/gem install *.gem --no-document --env-shebang
	popd
else
	$RUBY_PREFIX/bin/gem install $GEM --version $VERSION --no-document --env-shebang
fi
rm -rf $GEM_HOME/cache/*.gem
echo "-----> Done."
